#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get -y install haproxy

sudo echo "ENABLED=1" >> etc/default/haproxy

sudo echo "
frontend http_front
    bind *:80
    default_backend http_back
backend http_back
    balance roundrobin
    server 1523-web-01 34.75.41.111:80 check
    server 1523-web-02 34.73.135.215:80 check
" >> /etc/haproxy/haproxy.cfg
/etc/init.d/haproxy restart
